[package]
name = "ctunnel-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "2"
async-trait = "0.1"
tokio = { version = "1", features = ["io-util"]}

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "io-util"] }
